### ISSUE TITLE
Add a pre-reading study repo for `node-api`

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/planning#11]
Include a link to the cleaner version of Philip Roberts's "What the heck is the event loop?", as well as his website.

Per discussion with @gaand

**Comment by GA-MEB** [comment]
@gaand is [this version](https://youtu.be/8aGhZQkoFbQ) the one you were referring to?

**Comment by jrhorn424** [comment]
Closing due to resolution as https://github.com/ga-wdi-boston/js-async-study
