### ISSUE TITLE
Discuss `jasmine` alternatives for back-end testing

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/planning#12]
Jasmine runs in the browser, even when reports are generated on the command line. That means it is less-than-well suited for testing command line applications and APIs.

Any replacement should have an RSpec-like syntax. This affects `node-template` and `express-template`.

**Comment by gaand** [comment]
[The Node.js Way - Testing Essentials](http://fredkschott.com/post/2014/05/nodejs-testing-essentials/)

So maybe [mocha](https://mochajs.org/) and the other stuff from that as a starting point for the discussion?

**Comment by jrhorn424** [comment]
Closing due to resolution to use mocha.
